@TaskFlowPro.API_HostAddress = https://localhost:7069

POST {{TaskFlowPro.API_HostAddress}}/api/users
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com"
}

###
PUT https://localhost:7069/api/users/2
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Johnson",
  "email": "jane.johnson@example.com"
}

###
DELETE https://localhost:7069/api/users/3

###
POST https://localhost:7069/api/users
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "abc"
}

###
PUT https://localhost:7069/api/users/1
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "invalid-email"
}

###

POST https://localhost:7069/api/users
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "alice.brown@example.com"
}

###

PUT https://localhost:7069/api/users/4
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Updated",
  "email": "john.updated@example.com"
}

###
DELETE https://localhost:7069/api/users/1

###