@TaskFlowPro.API_HostAddress = https://localhost:7069

POST {{TaskFlowPro.API_HostAddress}}/api/users
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@example.com"
}

###